channels:
  - defaults
  - conda-forge
dependencies:
  # we don't really need tini as it's replace by the standard docker --init
  # flag, but add it to maintain compatibility with jupyter/docker-stacks
  - tini=0.18.0

  # the psycopg2 package is always required,
  # since the illumidesk stack depends on Postgress
  - psycopg2=2.8.*

  # conda's distribution of gmt deps don't play nice with python3.8.x
  # install python 3.7.x and monkey patch samesite cookie configs.
  - python=3.7

  # install mamba package manager
  - mamba

  # python/pip packages
  - pip
  - pip:
    # add these packages to all features to work
    - jupyter-contrib-nbextensions==0.5.*
    - jupyterhub==1.2.1
    - nbgitpuller==0.9.0
    - nbresuse==0.3.*
    - https://github.com/IllumiDesk/nbgrader/archive/v0.64.2.zip
    - jupyter-server-proxy==1.5.0
    - jupyterlab==2.2.8
    - nbconvert==5.6.1
    - notebook==6.1.5
